AVR498 : Atmel BLDC control on ATAVRMC301 with ATtiny861: mc_drv.h File Reference
mc_drv.h File Reference
Detailed Description
This file contains the function declarations.
Compiler: IAR EWAVR and GNU GCC for AVR
Supported devices: ATTiny861,ATTiny461,ATTiny261
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file mc_drv.h.
#include "bldc.h"
Functions
void mc_init_HW (void)
This function initializes the hardware/software resources required for motor driver.
Function Documentation
void mc_init_HW (void)
This function initializes the hardware/software resources required for motor driver.
Definition at line 238 of file mc_drv.c.
References ADCInit(), Clear_prescaler, PLLInit(), PortsInit(), PWMInit(), and Timer0Init().
Referenced by main().
{
  Clear_prescaler();
  PLLInit();
  PWMInit();
  ADCInit();
  // Initialize timer0 for commutation timing
  Timer0Init();
  // Initialize alternate function
  PortsInit();
}