AVR498 : Atmel BLDC control on ATAVRMC301 with ATtiny861: mc_drv.c File Reference
mc_drv.c File Reference
Detailed Description
This file contains the function declarations.
Compiler: IAR EWAVR and GNU GCC for AVR
Supported devices: ATTiny861,ATTiny461,ATTiny261
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file mc_drv.c.
#include "config.h"
#include "mc_drv.h"
Functions
void ADCInit (void)
__interrupt void Commutate ()
Commutates and prepares for new zero-cross detection.
void mc_init_HW (void)
This function initializes the hardware/software resources required for motor driver.
__interrupt void MotorPWMBottom ()
Timer/counter0 bottom overflow. Used for zero-cross detection.
void PLLInit (void)
void PortsInit (void)
void PWMInit (void)
void Set_cpu_prescaler (U8 x)
Set prescaler.
void Timer0Init (void)
Variables
ADMUXTableForward [6]
ADMUXTableReverse [6]
commTableForward [6]
commTableReverse [6]
volatile U8 nextCommutationStep
The commutation step that starts at next commutation.
volatile U8 nextDrivePattern
The power stage enable signals that will be output to the motor drivers at next commutation.
volatile U16 speedReferenceADC
ADC reading of external analog speed reference.
volatile U8 speedUpdated = FALSE
Flag that specifies whether a new external speed reference and a motor speed measurement is available.
volatile U8 zcPolarity
Polarity of the expected zero crossing.
zcTableForward [6]
zcTableReverse [6]
Function Documentation
void ADCInit (void)
Definition at line 210 of file mc_drv.c.
References ADC_PRESCALER_16, ADC_TRIGGER_SOURCE, ADMUX_REF_VOLTAGE, and speedReferenceADC.
Referenced by mc_init_HW().
{
  ADMUX = ADMUX_REF_VOLTAGE ;
  ADCSRA = (1 << ADEN) | (1 << ADSC) | (1 << ADIF) | (ADC_PRESCALER_16);
  while (ADCSRA & (1 << ADSC))
  {
  }
  speedReferenceADC = ADC;
  // Initialize the ADC for autotriggered operation on PWM timer overflow.
  ADCSRA = (1 << ADEN) | (0 << ADSC) | (1 << ADATE) | (1 << ADIF) | (0 << ADIE) | ADC_PRESCALER_16;
  ADCSRB = ADC_TRIGGER_SOURCE;
}
__interrupt void Commutate ()
Commutates and prepares for new zero-cross detection.
This interrupt service routine is triggered exactly when a commutation is scheduled. The commutation is performed instantly and Timer/counter0 is reset to measure the delay between commutation and zero-cross detection.
Commutation causes large transients on all phases for a short while that could cause false zero-cross detections. A zero cross detection hold-off period is therefore used to avoid any false readings. This is performed by using Timer/counter1 compare B. The compare is set to happen after the specified hold-off period. Timer/counter1 compare B interrupt handler then enables the zero-cross detection.
Definition at line 357 of file mc_drv.c.
References ADMUXTableForward, ADMUXTableReverse, CLEAR_ALL_TIMER0_INT_FLAGS, commTableForward, commTableReverse, DISABLE_ALL_TIMER0_INTS, nextCommutationStep, SET_TIMER1_INT_ZC_DETECTION, TC0_WRITE_TCNT0, zcPolarity, zcTableForward, and zcTableReverse.
{
  CLEAR_ALL_TIMER0_INT_FLAGS;
#if (DIRECTION_OF_ROTATION == CCW)
  // Commutate and clear commutation timer.
  TCCR1E = commTableReverse[nextCommutationStep];
#else
  // Commutate and clear commutation timer.
  TCCR1E = commTableForward[nextCommutationStep];
#endif
  TC0_WRITE_TCNT0(0);
#if (DIRECTION_OF_ROTATION == CCW)
  zcPolarity = zcTableReverse[nextCommutationStep];
  ADMUX = ADMUXTableReverse[nextCommutationStep];
#else
  zcPolarity = zcTableForward[nextCommutationStep];
  ADMUX = ADMUXTableForward[nextCommutationStep];
#endif
  nextCommutationStep ++;
  if (nextCommutationStep > 5)
  {
    nextCommutationStep = 0;
  }
  DISABLE_ALL_TIMER0_INTS;
  SET_TIMER1_INT_ZC_DETECTION;
}
void mc_init_HW (void)
This function initializes the hardware/software resources required for motor driver.
Definition at line 238 of file mc_drv.c.
References ADCInit(), Clear_prescaler, PLLInit(), PortsInit(), PWMInit(), and Timer0Init().
Referenced by main().
{
  Clear_prescaler();
  PLLInit();
  PWMInit();
  ADCInit();
  // Initialize timer0 for commutation timing
  Timer0Init();
  // Initialize alternate function
  PortsInit();
}
__interrupt void MotorPWMBottom ()
Timer/counter0 bottom overflow. Used for zero-cross detection.
This interrupt service routine is called every time the up/down counting PWM counter reaches bottom. An ADC reading on the active channel is automatically triggered at the same time as this interrupt is triggered. This is used to detect a zero crossing.
In the event of a zero crossing, the time since last commutation is stored and Timer/counter1 compare A is set up to trigger at the next commutation instant.
Definition at line 280 of file mc_drv.c.
References ADC_PRESCALER, ADC_PRESCALER_16, ADC_ZC_THRESHOLD, ADMUX_SPEED_REF, CLEAR_ALL_TIMER0_INT_FLAGS, CLEAR_ALL_TIMER1_INT_FLAGS, DISABLE_ALL_TIMER1_INTS, EDGE_FALLING, EDGE_RISING, SET_TIMER0_INT_COMMUTATION, speedReferenceADC, speedUpdated, TC0_READ_TCNT0, TC0_WRITE_TCNT0, TRUE, and zcPolarity.
{
  U16 temp;
  CLEAR_ALL_TIMER1_INT_FLAGS;
  ADCSRA = (1 << ADEN) | (1 << ADSC) | (1 << ADIF) | (ADC_PRESCALER_16);
  while (ADCSRA & (1 << ADSC))
  {
  }
  temp= ADC;
  if (((zcPolarity == EDGE_RISING) && (temp > ADC_ZC_THRESHOLD)) || ((zcPolarity == EDGE_FALLING) && (temp < ADC_ZC_THRESHOLD)))
  {
    U16 timeSinceCommutation;
    // Find time since last commutation
    TC0_READ_TCNT0(timeSinceCommutation);
    // Reset Timer before setting the next Commutation Period
    TC0_WRITE_TCNT0(0);
    OCR0A = timeSinceCommutation;
    speedUpdated = TRUE;
    SET_TIMER0_INT_COMMUTATION;
    CLEAR_ALL_TIMER0_INT_FLAGS;
    // Disable Timer/Counter1 overflow ISR.
    DISABLE_ALL_TIMER1_INTS;
    // Read speed reference.
    // Make sure that a sample is not in progress.
    while (ADCSRA & (1 << ADSC))
    {
    }
    // Change channel
    ADMUX = ADMUX_SPEED_REF;
    // Start conversion manually.
    ADCSRA |= (1 << ADSC);
    // Wait for conversion to complete.
    while((ADCSRA & (1 << ADSC)))
    {
    }
    speedReferenceADC = ADC;
    ADCSRA |= (1 << ADATE) | (0 << ADIE) | ADC_PRESCALER;
  }
}
void PLLInit (void)
Definition at line 185 of file mc_drv.c.
Referenced by mc_init_HW().
{
  //Enable fast peripheral clock (64MHz for Timer1).
  PLLCSR = (1 << PCKE);
}
void PortsInit (void)
Definition at line 227 of file mc_drv.c.
Referenced by mc_init_HW().
{
  //Set PWM pins as output. (PWM output is still controlled through TCCR1E register.)
  DDRB = (1 << PB0) | (1 << PB1) | (1 << PB2) | (1 << PB3) | (1 << PB4) | (1 << PB5)| (1 << PB6) ;
  // Disable digital input buffers on ADC channels.
  DIDR0 = (1 << ADC1D) | (1 << ADC2D) | (1 << ADC3D) | (1 << ADC4D) ;
}
void PWMInit (void)
Definition at line 192 of file mc_drv.c.
References PWM_TOP_VALUE, and TC1_WRITE_10_BIT_REGISTER.
Referenced by mc_init_HW().
{
  //Clear on up-counting.
  TCCR1A = (1 << COM1A1) | (0 << COM1A0) | (1 << PWM1A);
  //Set WGM to PWM6, dual slope mode.
  TCCR1D = (1 << WGM11) | (1 << WGM10);
  //Set top value.
  TC1_WRITE_10_BIT_REGISTER(OCR1C, PWM_TOP_VALUE);
  //Run timer at full speed.
  TCCR1B = (1 << CS10);
}
void Set_cpu_prescaler (U8 x)
Set prescaler.
This function set the internal CPU core clock prescaler
Parameters:
x Prescaler Value.
Definition at line 255 of file mc_drv.c.
   {
      U8 save_int=SREG&0x80;
      Disable_interrupt();
      CLKPR=(1<<CLKPCE);
      CLKPR=x;
      if(save_int) { Enable_interrupt(); }
   }
void Timer0Init (void)
Definition at line 179 of file mc_drv.c.
Referenced by mc_init_HW().
{
  // Set up Timer/counter0 for commutation timing, prescaler = 8.
  TCCR0B = ((0<<CS02)|(1<<CS01) |(0<<CS00));
}
Variable Documentation
ADMUXTableForward[6]
Initial value:
  {
    ADMUX_V,
    ADMUX_U,
    ADMUX_W,
    ADMUX_V,
    ADMUX_U,
    ADMUX_W
  }
Definition at line 58 of file mc_drv.c.
ADMUXTableReverse[6]
Initial value:
  {
    ADMUX_V,
    ADMUX_W,
    ADMUX_U,
    ADMUX_V,
    ADMUX_W,
    ADMUX_U
  }
Definition at line 75 of file mc_drv.c.
commTableForward[6]
Initial value:
 {
  DRIVE_PATTERN_STEP2_CW,
  DRIVE_PATTERN_STEP1_CW,
  DRIVE_PATTERN_STEP6_CW,
  DRIVE_PATTERN_STEP5_CW,
  DRIVE_PATTERN_STEP4_CW,
  DRIVE_PATTERN_STEP3_CW
}
Definition at line 92 of file mc_drv.c.
commTableReverse[6]
Initial value:
 {
  DRIVE_PATTERN_STEP5_CCW,
  DRIVE_PATTERN_STEP4_CCW,
  DRIVE_PATTERN_STEP3_CCW,
  DRIVE_PATTERN_STEP2_CCW,
  DRIVE_PATTERN_STEP1_CCW,
  DRIVE_PATTERN_STEP6_CCW
}
Definition at line 109 of file mc_drv.c.
volatile U8 nextCommutationStep
The commutation step that starts at next commutation.
The commutation step that starts at next commutation. This is used to keep track on where in the commutation cycle we are. Stored in register R11 for quick access
Definition at line 171 of file mc_drv.c.
Referenced by Commutate(), and mc_start_motor().
volatile U8 nextDrivePattern
The power stage enable signals that will be output to the motor drivers at next commutation.
This variable holds the pattern of enable signals that will be output to the power stage at next commutation. It is stored in register R13 for quick access.
Definition at line 156 of file mc_drv.c.
volatile U16 speedReferenceADC
ADC reading of external analog speed reference.
Definition at line 174 of file mc_drv.c.
Referenced by ADCInit(), mc_regulation_loop(), and MotorPWMBottom().
volatile U8 speedUpdated = FALSE
Flag that specifies whether a new external speed reference and a motor speed measurement is available.
Definition at line 177 of file mc_drv.c.
Referenced by mc_regulation_loop(), and MotorPWMBottom().
volatile U8 zcPolarity
Polarity of the expected zero crossing.
The polarity of the expected zero crossing. Could be eiter EDGE_FALLING or EDGE_RISING.
Definition at line 163 of file mc_drv.c.
Referenced by Commutate(), mc_start_motor(), and MotorPWMBottom().
zcTableForward[6]
Initial value:
 {
  EDGE_RISING,
  EDGE_FALLING,
  EDGE_RISING,
  EDGE_FALLING,
  EDGE_RISING,
  EDGE_FALLING
}
Definition at line 125 of file mc_drv.c.
zcTableReverse[6]
Initial value:
 {
  EDGE_FALLING,
  EDGE_RISING,
  EDGE_FALLING,
  EDGE_RISING,
  EDGE_FALLING,
  EDGE_RISING
}
Definition at line 142 of file mc_drv.c.